routes/web.php
<?php

use App\Http\Controllers\AboutController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\IndexController;
use App\Http\Controllers\IngredientController;
use App\Http\Controllers\RecipeController;
use App\Http\Controllers\SettingsController;
use App\Http\Controllers\UserController;
use App\Models\Ingredient;
use App\Models\Recipe;
use Illuminate\Routing\RouteGroup;
use Illuminate\Support\Facades\Route;
use Barryvdh\DomPDF\Facade\Pdf;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Index
Route::post('/generate',[IndexController::class,'generate'])->name('index.generate');
Route::get('/pdf',[IndexController::class,'pdf'])->name('index.pdf');
Route::resource('/', IndexController::class);

// About
Route::view('/about','about.index')->name('about');

Route::middleware('auth')->group(function () {
    // Users
    Route::middleware('can:is_admin')->group(function(){
        Route::resource('/user', UserController::class);
    });

    // Ingredients
    Route::put('/ingredient/lock/{ingredient}',[IngredientController::class,'lock'])->name('ingredient.lock');
    Route::resource('/ingredient', IngredientController::class);

    // Recipes
    Route::put('/recipe/bookmark/{recipe}',[RecipeController::class,'bookmark'])->name('recipe.bookmark');
    Route::resource('/recipe',RecipeController::class);

    //Settings
    Route::resource('/settings',SettingsController::class);
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Recipe.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Recipe extends Model
{
    use HasFactory;

    protected $fillable = [
        'user_id',
        'is_bookmarked'
    ];

    protected $casts = [
        'is_bookmarked' => 'boolean'
    ];

    public function ingredients(){
        return $this->belongsToMany(Ingredient::class,'ingredient_recipe','recipe_id','ingredient_id');
    }
}

app/Http/Controllers/RecipeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\Models\Ingredient;
use App\Models\Recipe;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class RecipeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $recipes = Recipe::with(['ingredients' => function ($q){
            $q->orderBy('category_id');
        }])->where('user_id',Auth::user()->id)->orderBy('is_bookmarked','desc')->orderBy('created_at')->get();
        $categoriesCount = Category::get()->count();

        foreach($recipes as $recipe){
            if($recipe->ingredients()->count() < $categoriesCount){
                $recipe->delete();
            }
        }

        return view('recipe.index',compact('recipes','categoriesCount'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Recipe  $recipe
     * @return \Illuminate\Http\Response
     */
    public function edit(Recipe $recipe)
    {
        $recipeIngredients = $recipe->ingredients()->orderBy('category_id')->get();
        $ingredients = Ingredient::select('id','category_id','title')->get();
        $categories = Category::select('id','title')->get();
        $categoriesCount = Category::get()->count();

        return view('recipe.edit',compact('recipe','recipeIngredients','ingredients','categories','categoriesCount'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Recipe  $recipe
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Recipe $recipe)
    {
        $categories = Category::select('id','title')->get();
        $categoriesCount = Category::get()->count();
        $recipeIngredients = [];

        for ($i=0; $i < $categoriesCount; $i++) { 
            $request->validate([
                ''.$categories[$i]->title.'' => 'required|exists:ingredients,id'
            ]);  
        }

        for ($i=0; $i < $categoriesCount; $i++) { 
            $category = $categories[$i]->title;
            array_push($recipeIngredients,$request->$category);
        }
        $recipe->ingredients()->sync($recipeIngredients);

        return redirect()->route('recipe.index')->with('success');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $recipe  = Recipe::find($id);
        
        if(!$recipe){
            $status = 404;
            $msg = 'Zutat nicht gefunden.';
        }
        else{
            $recipe->delete();
            $status = 200;
            $msg = 'Rezept wurde erfolgreich gelöscht.';
        }
        
        // Aufruf per JavaScript
        if(request()->ajax()){
            return response()->json([
                'status' => $status,
                'msg' => $msg
            ], $status);
        }
        
        // Aufruf per HTML
        if($status == 404){
            abort(404);
        }

        return redirect()->route('recipe.index')->with('success', $msg);
    }

    /**
     * Toggle is_bookmarked in recipe table
     *
     *  @param  \Illuminate\Http\Request    $request
     *  @param  \App\Models\Recipe          $recipe
     *  
     *  @return \Illuminate\Http\Response
     */
    public function bookmark(Request $request, Recipe $recipe){
        $recipe->is_bookmarked ? $recipe->is_bookmarked = false : $recipe->is_bookmarked = true;
        $recipe->save();

        return redirect()->route('recipe.index');
    }
}

resources/views/recipe/edit.blade.php
@extends('layouts.main')

@section('pageTitle','Rezept ändern')

@section('content')
    <h1>Rezept ändern</h1>
    <div class="button"><a href="{{route('recipe.index')}}" class="btn btn-outline-secondary">Alle Rezepte</a></div>

    @if (session('error'))
        <div class="alert alert-danger">
            {{ session('error') }}
        </div>
    @endif

    @dump(session('error'))
    
    <div id="form" class="form">
        <form action="{{route('recipe.update',$recipe->id)}}" method="post" enctype="multipart/form-data" novalidate>
            @csrf
            @method('PUT')
            @for ($i = 0; $i < $categoriesCount; $i++)
            <div class="form-group mb-2">
                <label for="{{$categories[$i]->title}}">{{$categories[$i]->title}}</label><br>
                <select name="{{$categories[$i]->title}}" id="{{$categories[$i]->title}}">
                    @foreach ($ingredients as $ingredient)
                            @if ($ingredient->category_id == $categories[$i]->id)
                                <option value="{{$ingredient->id}}" @if((old('id',$recipeIngredients[$i])) == $ingredient->id) selected @endif>{{$ingredient->title}}</option>
                            @endif
                    @endforeach
                </select>
            </div>
            @error($categories[$i]->title)
                <div class="invalid-feedback show-block">{{ucfirst($message)}}</div>
            @enderror
            @endfor
            
            <button type="submit" class="btn btn-dark">Speichern</button>
        </form>
    </div>

@endsection

resources/views/recipe/index.blade.php
@extends('layouts.main')

@section('pageTitle','Rezepte')

@section('content')

<h1>Rezepte</h1>

<p>In der Rezepte-Übersicht können Sie zuvor generierte Rezepte speichern, bearbeiten oder löschen. Es werden stets Ihre fünf zuletzt generierten Rezepte, sowie alle mit 'Speichern' markierte Rezepte angezeigt.</p>

@if( session('success') )
<div class="alert alert-success">{{ session('success') }}</div>
@endif
@if( session('error') )
<div class="alert alert-danger">{{ session('error') }}</div>
@endif

<table class="table table-hover table-settings">
  <thead>
    <tr>
      <th class="text-center">Salatbasis</th>
      <th class="text-center">Gemüse</th>
      <th class="text-center">Kohlenhydrate</th>
      <th class="text-center">Proteine</th>
      <th class="text-center">Fette</th>
      <th class="text-center">Früchte</th>
      <th class="text-center">Topping</th>
      <th class="text-center">Gespeichert</th>
    </tr>
  </thead>
  @foreach ($recipes as $recipe)
      <tr @if ($recipe->is_bookmarked) class="table-warning" @endif>
        @for ($i = 0; $i < $categoriesCount; $i++)
            <td class="text-center">{{$recipe->ingredients[$i]->title}}</td>
        @endfor
        <td class="text-center">
          <form action="{{route('recipe.bookmark',$recipe->id)}}" method="POST">
            @method('PUT')
            @csrf
            <button type="submit" class="btn btn-outline-dark" name="is_bookmarked">
            @if ($recipe->is_bookmarked)
                <i class="fa-solid fa-bookmark"></i>
            @else
                <i class="fa-regular fa-bookmark"></i>
            @endif
            </button>
          </form>
        </td>
        <td><a href="{{route('recipe.edit',$recipe->id)}}" class="btn btn-outline-secondary">Bearbeiten</a></td>
        <td>
          <form action="{{route('recipe.destroy',$recipe->id)}}" method="POST" class="delete" data-title="Löschen" data-body="Wollen Sie das Rezept löschen?" data-error="Rezept nicht gefunden!">
            @method('delete')
            @csrf
            <button type="submit" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#deleteModal">Löschen</button>
          </form>
        </td>
      </tr>
    @endforeach
</table>

@endsection