routes/web.php
<?php

use App\Http\Controllers\AboutController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\IndexController;
use App\Http\Controllers\IngredientController;
use App\Http\Controllers\RecipeController;
use App\Http\Controllers\SettingsController;
use App\Http\Controllers\UserController;
use App\Models\Ingredient;
use App\Models\Recipe;
use Illuminate\Routing\RouteGroup;
use Illuminate\Support\Facades\Route;
use Barryvdh\DomPDF\Facade\Pdf;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Index
Route::post('/generate',[IndexController::class,'generate'])->name('index.generate');
Route::get('/pdf',[IndexController::class,'pdf'])->name('index.pdf');
Route::resource('/', IndexController::class);

// About
Route::view('/about','about.index')->name('about');

Route::middleware('auth')->group(function () {
    // Users
    Route::middleware('can:is_admin')->group(function(){
        Route::resource('/user', UserController::class);
    });

    // Ingredients
    Route::put('/ingredient/lock/{ingredient}',[IngredientController::class,'lock'])->name('ingredient.lock');
    Route::resource('/ingredient', IngredientController::class);

    // Recipes
    Route::put('/recipe/bookmark/{recipe}',[RecipeController::class,'bookmark'])->name('recipe.bookmark');
    Route::resource('/recipe',RecipeController::class);

    //Settings
    Route::resource('/settings',SettingsController::class);
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'first_name',
        'last_name',
        'email',
        'password',
        'is_admin',
        'veg',
        'vgn',
        'gf',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'is_admin' => 'boolean',
        'vgn' => 'boolean',
        'veg' => 'boolean',
        'gf' => 'boolean'
    ];

    public function category()
    {
        return $this->belongsTo(Category::class, 'category_id', 'id');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\Ingredient;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();
        return view('user.index', compact('users'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::findOrFail($id);
        $ingredients = Ingredient::with('category:id,title')->where('user_id',$id)->get();
        return view('user.show',compact('user','ingredients'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $users = User::all();
        return view('user.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $request->validate([
            'first_name' => 'required|min:2',
            'last_name' => 'required|min:2',
            'email' => 'required|email:filter,dns',
            'admin' => 'boolean'
        ]);

        $adminCount = User::where('is_admin', 1)->count();
        if($user->is_admin && $adminCount == 1 && !$request->has('is_admin')) {
            return redirect()->back()->with('error', 'Es muss mindestens ein Admin-Benutzer vorhanden sein.');
        }

        $user->first_name = $request->first_name;
        $user->last_name = $request->last_name;
        $user->email = $request->email;
        $user->is_admin = $request->has('is_admin');
        $user->save();

        $user->update($request->all());
        return redirect()->route('user.index')->with('success', 'Benutzer '.$request->email.' wurde erfolgreich aktualisiert.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);
        if(!$user){
            $status = 404;
            $msg = 'Benutzer nicht gefunden';
        }
        elseif($user->is_admin == 1){
            $status = 403;
            $msg = 'Admin Benutzer können nicht gelöscht werden';
        }
        else{
            $user->delete();
            $status = 200;
            $msg = 'Benutzer '.$user->email.' wurde erfolgreich gelöscht';
        }

        //Aufruf per JavaScript
        if( request()->ajax() ){
            return response()->json(['status'=>$status,'msg'=>$msg],$status);
        }

        //Aufruf per HTML
        if( $status == 404 ){
            abort(404);
        }

        return redirect()->route('user.index')->with('success', $msg);
    }
}

resources/views/user/edit.blade.php
@extends('layouts.main')

@section('pageTitle','Benutzer ändern')

@section('content')
    <h1>Benutzer {{$user->email}} ändern</h1>
    <div class="button"><a href="{{route('user.index')}}" class="btn btn-outline-secondary">Alle Benutzer</a></div>

    @if (session('error'))
        <div class="alert alert-danger">
            {{ session('error') }}
        </div>
    @endif

    <div id="form" class="form">
        <form action="{{route('user.update',$user->id)}}" method="post" enctype="multipart/form-data" novalidate>
            @csrf
            @method('PUT')
            <div class="form-group mb-2">
                <label for="first_name">Vorname</label>
                <input type="text" class="form-control @error('first_name') is-invalid @enderror" id="first_name" name="first_name" value="{{old('first_name',$user->first_name)}}" required>
            </div>
            @error('first_name')
                <div class="invalid-feedback show-block">{{$message}}</div>w
            @enderror
            <div class="form-group mb-2">
                <label for="last_name">Nachname</label>
                <input type="text" class="form-control @error('last_name') is-invalid @enderror" id="last_name" name="last_name" value="{{old('last_name',$user->last_name)}}">
            </div>
            @error('last_name')
                <div class="invalid-feedback show-block">{{$message}}</div>
            @enderror
            <div class="form-group mb-2">
                <label for="email">E-Mail</label>
                <input type="text" class="form-control" id="email" name="email" value="{{old('email',$user->email)}}">
            </div>
            @error('email')
                <div class="invalid-feedback show-block">{{$message}}</div>
            @enderror

            <div class="form-check form-switch form-check-reverse">
                <label class="form-check-label" for="flexSwitchCheckReverse">Admin</label>
                <input class="form-check-input" type="checkbox" id="flexSwitchCheckReverse" @if ($user->is_admin) checked @endif name="is_admin">
            </div>

            <button type="submit" class="btn btn-dark">Speichern</button>
        </form>
    </div>

@endsection

resources/views/user/index.blade.php
@extends('layouts.main')

@section('pageTitle','Benutzer')

@section('content')

 <h1>Alle Benutzer</h1>

 @if( session('success') )
 <div class="alert alert-success">{{ session('success') }}</div>
 @endif

<table class="table table-hover table-settings">
  <thead>
    <tr>
      <th>#</th>
      <th>Vorname</th>
      <th>Nachname</th>
      <th>E-Mail</th>
      <th class="text-center">Admin</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  @foreach ($users as $user)
    <tr>
      <td scope="row">{{$user->id}}</td>
      <td>{{$user->first_name}}</td>
      <td>{{$user->last_name}}</td> 
      <td>{{$user->email}}</td>
      <td class="text-center">@if ($user->is_admin) <i class="fa-solid fa-check"> @endif</td>
      <td><a href="{{route('user.show',$user->id)}}" class="btn btn-outline-secondary">Anzeigen</a></td>
      <td><a href="{{route('user.edit',$user->id)}}" class="btn btn-outline-secondary">Bearbeiten</a></td>
      <td>
        <form action="{{route('user.destroy',$user->id)}}" method="POST" class="delete" data-title="{{$user->email}}" data-body="Wollen Sie den Benutzer <strong>{{$user->email}}</strong> löschen?" data-error="@if ($user->is_admin) Admin Benutzer können nicht gelöscht werden! @else Benutzer nicht gefunden! @endif">
          @method('DELETE')
          @csrf
          @if ($user->is_admin)
          <span class="d-inline-block" tabindex="0" data-bs-toggle="popover" data-bs-trigger="hover focus" data-bs-content="Admins können nicht gelöscht werden! Bitte entfernen Sie zunächst die Adminrechte dieses Users, bevor Sie ihn löschen.">
          @endif
            <button type="submit" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#deleteModal" @if($user->is_admin) disabled @endif>Löschen</button>
          @if ($user->is_admin)
          </span>
          @endif
        </form>
      </td>
    </tr>
  @endforeach
</table>


@endsection

resources/views/user/show.blade.php
@extends('layouts.main')

@section('pageTitle','Benutzer')

@section('content')

<h1>{{$user->first_name}} {{$user->last_name}}</h1>
<div class="button"><a href="{{route('user.index')}}" class="btn btn-outline-secondary">Alle Benutzer</a></div>

<div >
    <label for="first_name">Vorname</label>
    <input class="form-control w-25" type="text" value="{{$user->first_name}}" id="first_name" disabled>
    <label for="last_name">Nachname</label>
    <input class="form-control w-25" type="text" value="{{$user->last_name}}" id="last_name" disabled>
    <label for="email">E-Mail Adresse</label>
    <input class="form-control w-25" type="text" value="{{$user->email}}" id="email" disabled>
</div>


<h5 class="mt-5 mb-2">Persönliche Zutaten:</h5>

<table class="table table-hover table-settings">
    <thead>
      <tr>
        <th>Name</th>
        <th>Kategorie</th>
        <th class="text-center">Energie</th>
        <th class="text-center">Proteine</th>
        <th class="text-center">Kohlenhydrate</th>
        <th class="text-center">Fette</th>
        <th class="text-center">Vegan</th>
        <th class="text-center">Vegetarisch</th>
        <th class="text-center">Glutenfrei</th>
      </tr>
    </thead>
    @foreach ($ingredients as $ingredient)
    <tr>
      <td scope="row">{{$ingredient->title}}</td> 
      <td>{{$ingredient->category->title}}</td>
      <td class="text-center">{{$ingredient->energy}}kcal</td>
      <td class="text-center">{{$ingredient->protein}}g</td>
      <td class="text-center">{{$ingredient->carbohydrate}}g</td>
      <td class="text-center">{{$ingredient->fat}}g</td>
      <td class="text-center">@if ($ingredient->vgn) <i class="fa-solid fa-check"> @endif</td>
      <td class="text-center">@if ($ingredient->veg) <i class="fa-solid fa-check"> @endif</td>
      <td class="text-center">@if ($ingredient->gf) <i class="fa-solid fa-check"> @endif</td>
    </tr>
    @endforeach
  </table>

@endsection