routes/web.php
<?php

use App\Http\Controllers\AboutController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\IndexController;
use App\Http\Controllers\IngredientController;
use App\Http\Controllers\RecipeController;
use App\Http\Controllers\SettingsController;
use App\Http\Controllers\UserController;
use App\Models\Ingredient;
use App\Models\Recipe;
use Illuminate\Routing\RouteGroup;
use Illuminate\Support\Facades\Route;
use Barryvdh\DomPDF\Facade\Pdf;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Index
Route::post('/generate',[IndexController::class,'generate'])->name('index.generate');
Route::get('/pdf',[IndexController::class,'pdf'])->name('index.pdf');
Route::resource('/', IndexController::class);

// About
Route::view('/about','about.index')->name('about');

Route::middleware('auth')->group(function () {
    // Users
    Route::middleware('can:is_admin')->group(function(){
        Route::resource('/user', UserController::class);
    });

    // Ingredients
    Route::put('/ingredient/lock/{ingredient}',[IngredientController::class,'lock'])->name('ingredient.lock');
    Route::resource('/ingredient', IngredientController::class);

    // Recipes
    Route::put('/recipe/bookmark/{recipe}',[RecipeController::class,'bookmark'])->name('recipe.bookmark');
    Route::resource('/recipe',RecipeController::class);

    //Settings
    Route::resource('/settings',SettingsController::class);
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Ingredient.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Kyslik\ColumnSortable\Sortable;

class Ingredient extends Model
{
    use HasFactory, Sortable;

    protected $fillable = [
        'title',
        'category_id',
        'energy',
        'protein',
        'carbohydrate',
        'fat',
        'vgn',
        'veg',
        'gf'
    ];

    protected $casts = [
        'category_id' => 'integer',
        'vgn' => 'boolean',
        'veg' => 'boolean',
        'gf' => 'boolean'
    ];

    public $sortable = [
        'title',
        'category_id',
        'energy',
        'protein',
        'carbohydrate',
        'fat',
        'vgn',
        'veg',
        'gf'
    ];

    public function category()
    {
        return $this->belongsTo(Category::class, 'category_id', 'id');
    }

    public function lockedIngredients()
    {
        return $this->belongsToMany(User::class,'ingredient_user','ingredient_id','user_id','id','id');
    }

}

app/Http/Controllers/IngredientController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\Models\Ingredient;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class IngredientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {        
        // Add value 'count = 1' to categories with just one ingredient
        if(Auth::user()->is_admin == 1){
            $ingredients = Ingredient::sortable()->where('user_id',null)->orWhere('user_id',Auth::user()->id)->orderBy('user_id','desc')->paginate(15);
            foreach($ingredients as $ingredient){
                if((Ingredient::where('category_id',$ingredient->category_id)->where('user_id',NULL)->count() == 1)){
                    $ingredient->count = 1;
                }
            }
        }
        else {
            $ingredients = Ingredient::sortable()->where('user_id',null)->orWhere('user_id',Auth::user()->id)->orderBy('user_id','desc')->paginate(15);
            foreach($ingredients as $ingredient){
                $userId = auth()->user()->id;
                $ingredientCount = Ingredient::where('category_id',$ingredient->category_id)
                                             ->whereDoesntHave('lockedIngredients', function($query) use ($userId) { 
                                                $query->where('user_id',$userId);
                                             })
                                             ->where('user_id',NULL)
                                             ->orWhere('user_id',auth()->user()->id)
                                             ->count();
                if(($ingredientCount == 1)){
                    $ingredient->count = 1;
                }
            }
        }

        if(!empty($_GET['sort'])){
            $request->session()->put('sort','sort='.$_GET['sort'].'&direction='.$_GET['direction']);
        }
        if(!empty($_GET['page'])){
            $request->session()->put('page','page='.$_GET['page']);
        }
        if(empty($_GET['page']) && empty($_GET['sort'])){
            $request->session()->forget('page');
            $request->session()->forget('sort');
        }

        return view('ingredient.index', compact('ingredients'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::select('id', 'title')->get();
        return view('ingredient.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required|min:2',
            'category_id' => 'required|exists:categories,id',
            'energy' => 'required|numeric',
            'protein' => 'required|numeric',
            'carbohydrate' => 'required|numeric',
            'fat' => 'required|numeric',
        ]);

        $ingredient = new Ingredient();
        $ingredient->title = $request->title;
        $ingredient->category_id = $request->category_id;
        $ingredient->energy = $request->energy;
        $ingredient->protein = $request->protein;
        $ingredient->carbohydrate = $request->carbohydrate;
        $ingredient->fat = $request->fat;
        $ingredient->vgn = $request->has('vgn');
        $ingredient->veg = $request->has('veg');
        $ingredient->gf = $request->has('gf');
        if(!auth()->user()->is_admin || $request->has('personal')){
            $ingredient->user_id = auth()->user()->id;
        }
        $ingredient->save();

        return redirect()->route('ingredient.index')->with('success', 'Die Zutat '.$ingredient->title.' wurde erfolgreich erstellt.');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Ingredient  $ingredient
     * @return \Illuminate\Http\Response
     */
    public function edit(Ingredient $ingredient)
    {
        $categories = Category::select('id', 'title')->get();
        if(auth()->user()->is_admin && !$ingredient->user_id){
            return view('ingredient.edit', compact('ingredient', 'categories'));
        }
        elseif(auth()->user()->id == $ingredient->user_id){
            return view('ingredient.edit', compact('ingredient', 'categories'));
        }
        else{
            abort(404);
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Ingredient  $ingredient
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Ingredient $ingredient)
    {
        $request->validate([
            'title' => 'required|min:2',
            'category_id' => 'required|exists:categories,id',
            'energy' => 'required|numeric',
            'protein' => 'required|numeric',
            'carbohydrate' => 'required|numeric',
            'fat' => 'required|numeric',
        ]);

        
        $ingredientCount = Ingredient::where('category_id',$ingredient->category_id)->where('user_id',NULL)->count();

        $category = Category::select('id', 'title')->get();
        $userId = auth()->user()->id;

        $lockedIngredientCount = Ingredient::where('category_id',$ingredient->category_id)->whereHas('lockedIngredients',function($query) use ($userId) {$query->where('user_id',$userId);})->count();

        $allIngredientsCount = Ingredient::where('category_id',$ingredient->category_id)->where(function ($query) use ($userId){$query->where('user_id',NULL)->orWhere('user_id',$userId);})->count();



        if(auth()->user()->is_admin){
            if(($ingredientCount == 1) && ($request->input('category_id') != $ingredient->category_id*1 || $request->has('personal'))){ 
                return redirect()->back()->with('error', 'Es muss mindestens eine allgemeine Zutat in der Kategorie \''.$category[$ingredient->category_id-1]->title.'\' vorhanden sein!');
            }  
        }

        if(!auth()->user()->is_admin){
            if(($allIngredientsCount - $lockedIngredientCount == 1) && ($request->input('category_id') != $ingredient->category_id*1)){
                return redirect()->back()->with('error', 'Es muss mindestens eine Zutat in der Kategorie \''.$category[$ingredient->category_id-1]->title.'\' verfügbar sein! Entsperren Sie zunächst eine andere Zutat derselben Kategorie oder fügen Sie eine neue Zutat mit dieser Kategorie hinzu.');
            }
        }

        $ingredient->title = $request->title;
        $ingredient->category_id = $request->category_id;
        $ingredient->energy = $request->energy;
        $ingredient->protein = $request->protein;
        $ingredient->carbohydrate = $request->carbohydrate;
        $ingredient->fat = $request->fat;
        $ingredient->vgn = $request->has('vgn');
        $ingredient->veg = $request->has('veg');
        $ingredient->gf = $request->has('gf');
        if(auth()->user()->is_admin){
            if($request->has('personal')){
                $ingredient->user_id = auth()->user()->id;
            }
            else{
                $ingredient->user_id = NULL;
            }
        }
        $ingredient->save();
        
        return redirect()->route('ingredient.index')->with('success', 'Zutat '.$request->title.' wurde erfolgreich aktualisiert.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Ingredient  $ingredient->id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $ingredient = Ingredient::find($id);
        if(auth()->user()->is_admin){
            $ingredientCount = Ingredient::where('category_id',$ingredient->category_id)->where('user_id',NULL)->count();
        }
        else{
            $userId = auth()->user()->id;
            $ingredientCount = Ingredient::where('category_id',$ingredient->category_id)->whereDoesntHave('lockedIngredients', function($query) use ($userId) { 
            $query->where('user_id',$userId);})->where('user_id',NULL)->orWhere('user_id',auth()->user()->id)->count();
        }
        
        if(!$ingredient){
            $status = 404;
            $msg = 'Zutat nicht gefunden.';
        }
        elseif($ingredientCount == 1){
            $category = Category::select('id', 'title')->get();
            $status = 403;
            $msg = 'Es muss mindestens eine Zutat in der Kategorie \''.$category[$ingredient->category_id-1]->title.'\' vorhanden sein!';
        }
        else{
            $ingredient->delete();
            $status = 200;
            $msg = 'Zutat '.$ingredient->title.' wurde erfolgreich gelöscht.';
        }
        
        // Aufruf per JavaScript
        if(request()->ajax()){
            return response()->json([
                'status' => $status,
                'msg' => $msg
            ], $status);
        }

        // Aufruf per HTML
        if($status == 404){
            abort(404);
        }
        
        return redirect()->route('ingredient.index')->with('success', $msg);
    }

    /**
     * Add specified ingredient in ingredient_user table 
     *
     * @param   \App\Models\Ingredient    $ingredient
     * @param   \Illuminate\Http\Request  $request
     *
     * @return  \Illuminate\Http\Response
     */
    public function lock(Ingredient $ingredient,Request $request){
        $category = Category::select('id', 'title')->get();
        $userId = auth()->user()->id;

        $lockedIngredientCount = Ingredient::where('category_id',$ingredient->category_id)->whereHas('lockedIngredients',function($query) use ($userId) {$query->where('user_id',$userId);})->count();

resources/views/ingredient/create.blade.php
@extends('layouts.main')

@section('pageTitle','Zutat hinzufügen')

@section('content')
    <h1>Neue Zutat hinzufügen</h1>
    <div class="button"><a href="{{route('ingredient.index')}}" class="btn btn-outline-secondary">Alle Zutaten</a></div>


    <div id="form" class="form">
        <form action="{{route('ingredient.store')}}" method="post" enctype="multipart/form-data" novalidate>
            @csrf
            {{-- Title --}}
            <div class="form-group mb-2">
                <label for="title">Name</label>
                <input type="text" class="form-control @error('title') is-invalid @enderror" id="title" name="title" value="{{old('title')}}" required>
            </div>
            @error('title')
                <div class="invalid-feedback show-block">{{$message}}</div> {{-- Warum "display: none" bei invalid-feedback?  --}}
            @enderror
            {{-- Category --}}
            <div class="form-group mb-2">
                <label for="category_id">Kategorie</label>
                <select class="form-select" name="category_id" id="category_id">
                    <option value="">Kategorie auswählen</option>
                    @foreach ($categories as $category)
                        <option value="{{$category->id}}" @if((old('category_id')) == $category->id) selected @endif>{{$category->title}}</option>
                    @endforeach
                </select>
            </div>
            @error('category_id')
                <div class="invalid-feedback show-block">{{$message}}</div>
            @enderror
            {{-- Energy --}}
            <div class="form-group mb-2">
                <label for="energy">Energie</label>
                <input type="number" class="form-control" id="energy" name="energy" value="{{old('energy')}}">
            </div>
            @error('energy')
                <div class="invalid-feedback show-block">{{$message}}</div>
            @enderror
            {{-- Protein --}}
            <div class="form-group mb-2">
                <label for="protein">Proteine</label>
                <input type="number" class="form-control" id="protein" name="protein" value="{{old('protein')}}">
            </div>
            @error('protein')
                <div class="invalid-feedback show-block">{{$message}}</div>
            @enderror
            {{-- Carbohydrate --}}
            <div class="form-group mb-2">
                <label for="carbohydrate">Kohlenhydrate</label>
                <input type="number" class="form-control" id="carbohydrate" name="carbohydrate" value="{{old('carbohydrate')}}">
            </div>
            @error('carbohydrate')
                <div class="invalid-feedback show-block">{{$message}}</div>
            @enderror
            {{-- Fat --}}
            <div class="form-group mb-2">
                <label for="fat">Fette</label>
                <input type="number" class="form-control" id="fat" name="fat" value="{{old('fat')}}">
            </div>
            @error('fat')
                <div class="invalid-feedback show-block">{{$message}}</div>
            @enderror
            {{-- Vegan --}}
            <div class="form-check form-switch form-check-reverse">
                <label class="form-check-label" for="flexSwitchCheckReverse">Vegan</label>
                <input class="form-check-input" type="checkbox" id="flexSwitchCheckReverse" name="vgn" {{old('vgn') == 1 ? 'checked' : ''}}>
            </div>
            {{-- Vegetarian --}}
            <div class="form-check form-switch form-check-reverse">
                <label class="form-check-label" for="flexSwitchCheckReverse">Vegetarisch</label>
                <input class="form-check-input" type="checkbox" id="flexSwitchCheckReverse" name="veg" {{old('veg') == 1 ? 'checked' : ''}}>
            </div>
            {{-- Glutenfree --}}
            <div class="form-check form-switch form-check-reverse">
                <label class="form-check-label" for="flexSwitchCheckReverse">Glutenfrei</label>
                <input class="form-check-input" type="checkbox" id="flexSwitchCheckReverse" name="gf" {{old('gf') == 1 ? 'checked' : ''}}>
            </div>
            {{-- Save as personal ingredient --}}
            @if(auth()->user()->is_admin)
            <div class="form-check form-switch form-check-reverse">
                <label class="form-check-label" for="flexSwitchCheckReverse">Als persönliche Zutat speichern</label>
                <input class="form-check-input" type="checkbox" id="flexSwitchCheckReverse" name="personal" {{old('user_id') ? 'checked' : ''}}>
            </div>
            @endif


            <button type="submit" class="btn btn-dark">Speichern</button>
        </form>
    </div>

@endsection

resources/views/ingredient/edit.blade.php
@extends('layouts.main')

@section('pageTitle','Zutat ändern')

@section('content')
    <h1>Zutat {{$ingredient->title}} ändern</h1>
    <div class="button"><a href="{{route('ingredient.index')}}" class="btn btn-outline-secondary">Alle Zutaten</a></div>

    @if (session('error'))
        <div class="alert alert-danger">
            {{ session('error') }}
        </div>
    @endif

    <div id="form" class="form">
        <form action="{{route('ingredient.update',$ingredient->id)}}" method="post" enctype="multipart/form-data" novalidate>
            @csrf
            @method('PUT')
            {{-- Title --}}
            <div class="form-group mb-2">
                <label for="title">Name</label>
                <input type="text" class="form-control @error('title') is-invalid @enderror" id="title" name="title" value="{{old('title',$ingredient->title)}}" required>
            </div>
            @error('title')
                <div class="invalid-feedback show-block">{{$message}}</div>
            @enderror
            {{-- Category --}}
            <div class="form-group mb-2">
                <label for="category_id">Kategorie</label>
                <select class="form-select" name="category_id" id="category_id">
                    @foreach ($categories as $category)
                        <option value="{{$category->id}}" @if((old('category_id',$ingredient->category_id)) == $category->id) selected @endif>{{$category->title}}</option>
                    @endforeach
                </select>
            </div>
            @error('category_id')
                <div class="invalid-feedback show-block">{{$message}}</div>
            @enderror
            {{-- Energy --}}
            <div class="form-group mb-2">
                <label for="energy">Energie</label>
                <input type="number" class="form-control" id="energy" name="energy" value="{{old('energy',$ingredient->energy)}}">
            </div>
            @error('energy')
                <div class="invalid-feedback show-block">{{$message}}</div>
            @enderror
            {{-- Protein --}}
            <div class="form-group mb-2">
                <label for="protein">Proteine</label>
                <input type="number" class="form-control" id="protein" name="protein" value="{{old('protein',$ingredient->protein)}}">
            </div>
            @error('protein')
                <div class="invalid-feedback show-block">{{$message}}</div>
            @enderror
            {{-- Carbohydrate --}}
            <div class="form-group mb-2">
                <label for="carbohydrate">Kohlenhydrate</label>
                <input type="number" class="form-control" id="carbohydrate" name="carbohydrate" value="{{old('carbohydrate',$ingredient->carbohydrate)}}">
            </div>
            @error('carbohydrate')
                <div class="invalid-feedback show-block">{{$message}}</div>
            @enderror
            {{-- Fat --}}
            <div class="form-group mb-2">
                <label for="fat">Fette</label>
                <input type="number" class="form-control" id="fat" name="fat" value="{{old('fat',$ingredient->fat)}}">
            </div>
            @error('fat')
                <div class="invalid-feedback show-block">{{$message}}</div>
            @enderror
            {{-- Vegan --}}
            <div class="form-check form-switch form-check-reverse">
                <label class="form-check-label" for="flexSwitchCheckReverse">Vegan</label>
                <input class="form-check-input" type="checkbox" id="flexSwitchCheckReverse" @if ($ingredient->vgn) checked @endif name="vgn">
            </div>
            {{-- Vegetarian --}}
            <div class="form-check form-switch form-check-reverse">
                <label class="form-check-label" for="flexSwitchCheckReverse">Vegetarisch</label>
                <input class="form-check-input" type="checkbox" id="flexSwitchCheckReverse" @if ($ingredient->veg) checked @endif name="veg">
            </div>
            {{-- Glutenfree --}}
            <div class="form-check form-switch form-check-reverse">
                <label class="form-check-label" for="flexSwitchCheckReverse">Glutenfrei</label>
                <input class="form-check-input" type="checkbox" id="flexSwitchCheckReverse" @if ($ingredient->gf) checked @endif name="gf">
            </div>
            {{-- Personal ingredient --}}
            @if (auth()->user()->is_admin)
            <div class="form-check form-switch form-check-reverse">
                <label class="form-check-label" for="flexSwitchCheckReverse">persönliche Zutat</label>
                <input class="form-check-input" type="checkbox" id="flexSwitchCheckReverse" name="personal" {{$ingredient->user_id ? 'checked' : ''}}>
            </div>              
            @endif

            <button type="submit" class="btn btn-dark">Speichern</button>
        </form>
    </div>

@endsection

resources/views/ingredient/index.blade.php
@extends('layouts.main')

@section('pageTitle','Zutaten')

@section('content')

<h1>Zutaten</h1>

@can('is_admin')
<p class="description">In der Zutaten-Übersicht haben Sie die Möglichkeit neue Zutaten hinzufügen, zu bearbeiten oder zu löschen. Zudem besteht die Möglichkeit eine Zutat als persönliche Zutat abzuspeichern, diese wird dann nicht mehr berücksichtigt, wenn andere User den Generator verwenden</p>
@endcan
@can('is_user')
<p class="description">In der Zutaten-Übersicht haben Sie die Möglichkeit Zutaten zu sperren, die nicht mehr vom Generator berücksichtigt werden, sowie neue persönliche hinzuzufügen, zu bearbeiten oder zu löschen.</p>
@endcan

@if( session('success') )
<div class="alert alert-success">{{ session('success') }}</div>
@endif
@if( session('error') )
<div class="alert alert-danger" id="error">{{ session('error') }}</div>
@endif

<table class="table table-hover table-settings">
  <thead>
    <tr>
      <th>@sortablelink('title','Name')</th>
      <th>@sortablelink('category.title','Kategorie')</th>
      <th class="text-center">@sortablelink('energy','Energie')</th>
      <th class="text-center">@sortablelink('protein','Proteine')</th>
      <th class="text-center">@sortablelink('carbohydrate','Kohlenhydrate')</th>
      <th class="text-center">@sortablelink('fat','Fette')</th>
      <th class="text-center">@sortablelink('vgn','Vegan')</th>
      <th class="text-center">@sortablelink('veg','Vegetarisch')</th>
      <th class="text-center">@sortablelink('gf','Glutenfrei')</th>
    </tr>
  </thead>
  @foreach ($ingredients as $ingredient)
  <tr @if (auth()->user()->id == $ingredient->user_id) class="table-warning"  @endif
      @if (lockedIngredients($ingredient,$ingredient->id,auth()->user()->id)) class="table-light" @endif
      id="{{$ingredient->id}}">
    <td scope="row">{{$ingredient->title}}</td> 
    <td>{{$ingredient->category->title}}</td>
    <td class="text-center">{{$ingredient->energy}}kcal</td>
    <td class="text-center">{{$ingredient->protein}}g</td>
    <td class="text-center">{{$ingredient->carbohydrate}}g</td>
    <td class="text-center">{{$ingredient->fat}}g</td>
    <td class="text-center">@if ($ingredient->vgn) <i class="fa-solid fa-check"> @endif</td>
    <td class="text-center">@if ($ingredient->veg) <i class="fa-solid fa-check"> @endif</td>
    <td class="text-center">@if ($ingredient->gf) <i class="fa-solid fa-check"> @endif</td>
    @if (($ingredient->user_id == auth()->user()->id)||(auth()->user()->is_admin == 1 && !$ingredient->user_id))
    <td><a href="{{route('ingredient.edit',$ingredient->id)}}" class="btn btn-outline-secondary">Bearbeiten</a></td>
    <td>
      <form action="{{route('ingredient.destroy',$ingredient->id)}}" method="POST" class="delete" data-title="{{$ingredient->title}}" data-body="Wollen Sie die Zutat <strong>{{$ingredient->title}}</strong> löschen?" data-error="Zutat nicht gefunden!">
        @method('delete')
        @csrf
        @if ($ingredient->count == 1)
          <span class="d-inline-block" tabindex="0" data-bs-toggle="popover" data-bs-trigger="hover focus" data-bs-content="Es muss mindestens eine Zutat in der Kategorie '{{$ingredient->category->title}}' vorhanden sein!">
        @endif
        <button type="submit" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#deleteModal" @if ($ingredient->count == 1) disabled @endif>Löschen</button>
      </form>
    </td>
    @endif
    @if ((!auth()->user()->is_admin) && (!$ingredient->user_id))
    <td colspan="2">
      @if(lockedIngredients($ingredient,$ingredient->id,auth()->user()->id))
      <form action="{{route('ingredient.lock',[$ingredient->id,'#'.$ingredient->id])}}" method="POST">
        @method('PUT')
        @csrf
        <button type="submit" class="btn btn-outline-danger">Entsperren</button>
      </form>
      @else
      <form action="{{route('ingredient.lock',[$ingredient->id,'#'.$ingredient->id])}}" method="POST">
        @method('PUT')
        @csrf
        <button type="submit" class="btn btn-outline-danger">Sperren</button>
      </form>
      @endif
    </td>
    @endif
  </tr>
  @endforeach
</table>

<div class="myPagination">
{{-- {{ $ingredients->links("pagination::bootstrap-4")}} --}}
{{$ingredients->appends(Request::except('page'))->links("pagination::bootstrap-4")}}
</div>


<div class="button"><a href="{{route('ingredient.create')}}" class="btn btn-outline-secondary">Zutat hinzufügen</a></div>  

@endsection