routes/web.php
<?php

use App\Http\Controllers\AboutController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\IndexController;
use App\Http\Controllers\IngredientController;
use App\Http\Controllers\RecipeController;
use App\Http\Controllers\SettingsController;
use App\Http\Controllers\UserController;
use App\Models\Ingredient;
use App\Models\Recipe;
use Illuminate\Routing\RouteGroup;
use Illuminate\Support\Facades\Route;
use Barryvdh\DomPDF\Facade\Pdf;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Index
Route::post('/generate',[IndexController::class,'generate'])->name('index.generate');
Route::get('/pdf',[IndexController::class,'pdf'])->name('index.pdf');
Route::resource('/', IndexController::class);

// About
Route::view('/about','about.index')->name('about');

Route::middleware('auth')->group(function () {
    // Users
    Route::middleware('can:is_admin')->group(function(){
        Route::resource('/user', UserController::class);
    });

    // Ingredients
    Route::put('/ingredient/lock/{ingredient}',[IngredientController::class,'lock'])->name('ingredient.lock');
    Route::resource('/ingredient', IngredientController::class);

    // Recipes
    Route::put('/recipe/bookmark/{recipe}',[RecipeController::class,'bookmark'])->name('recipe.bookmark');
    Route::resource('/recipe',RecipeController::class);

    //Settings
    Route::resource('/settings',SettingsController::class);
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav me-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ms-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/main.blade.php
<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>@yield('pageTitle',config('app.name') )</title>
    <link rel="stylesheet" href="/css/font-awesome/css/font-awesome.css">
    <link rel="stylesheet" href="/css/bootstrap/css/bootstrap.min.css" >
    <link rel="stylesheet" href="/css/style.css">
</head>
<body>
  {{-- Navbar --}}
  <nav class="navbar navbar-expand-lg navbar-light bg-light" id="top">
    <div class="container-fluid">
      {{-- Navbar Collapse --}}
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mb-2 mb-lg-0 vstack">
          {{-- Home --}}
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="/"><i class="fa-solid fa-bowl-food"></i></a>
          </li>
          {{-- About --}}
          @guest 
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{{route('about')}}">Über</a>
          </li>
          @endguest
          {{-- Users --}}
          @auth
          @can('is_admin')
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{{route('user.index')}}">Benutzer</a>
          </li>
          @endcan
          @endauth
          {{-- Ingredients --}}
          @auth
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{{route('ingredient.index')}}">Zutaten</a>
          </li>
          @endauth
          {{-- Recipes --}}
          @auth
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{{route('recipe.index')}}">Rezepte</a>
          </li>
          @endauth
          {{-- Settings --}}
          @auth
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{{route('settings.index')}}">Einstellungen</a>
          </li>
          @endauth
          {{-- Login --}}
          <li class="nav-item ms-lg-auto login-button">
            <a class="nav-link" data-bs-toggle="offcanvas" data-bs-target="#offcanvasRight" aria-controls="offcanvasRight" role="button" href="#offcanvasExample">
              <i class="fa-solid fa-user"></i> 
            </a>
            <div class="collapse" id="collapseExample">
              <div class="card card-body">
                @auth
                  <form action="{{ route('logout') }}" method="post">
                    @csrf
                    <button type="submit" class="btn btn-outline-secondary">Logout</button>
                  </form>
                @else
                  @if(Route::has('login'))
                    <a href="{{ route('login') }}" class="btn btn-outline-secondary">Login</a>
                  @endif
                  @if(Route::has('register'))
                    <a href="{{ route('register') }}" class="btn btn-outline-secondary">Register</a>
                  @endif
                @endauth
              </div>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  {{-- Content --}}
  <div id="wrapper" class="container-fluid">
    @yield('content')
  </div>

  {{-- Modal Delete --}}
  <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Modal title</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          ...
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Abbrechen</button>
          <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Löschen</button>
        </div>
      </div>
    </div>
  </div>

  {{-- Offcanvas Login --}}
  <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasRight" aria-labelledby="offcanvasRightLabel">
    <div class="offcanvas-header">
      <h5 class="offcanvas-title" id="offcanvasRightLabel">Login</h5>
      <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
      <div class="card card-body">
        @auth
          <form action="{{ route('logout') }}" method="post">
            @csrf
            <button type="submit" class="btn btn-outline-secondary">Logout</button>
          </form>
        @else
          @if(Route::has('login'))
            <a href="{{ route('login') }}" class="btn btn-outline-secondary">Login</a>
          @endif
          @if(Route::has('register'))
            <a href="{{ route('register') }}" class="btn btn-outline-secondary">Register</a>
          @endif
        @endauth
      </div>
    </div>
  </div>

  {{-- <script src="/css/bootstrap/js/bootstrap.min.js"></script> --}}
  <script src="/js/jquery-3.6.0.min.js"></script>
  <script src="/css/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="/js/fontawesome.js"></script>
  <script src="/js/script.js"></script>
</body>
</html>